(define (make-account balance password)
  (define (withdraw amount)
    (if (< balance amount)
        (error "no enough balance")
        (begin (set! balance (- balance amount))
               balance)))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch pass arg)
    (if (eq? pass password)
        (cond
         ((eq? arg 'withdraw) withdraw)
         ((eq? arg 'deposit) deposit)
         (else (error "requested procedure does not exist")))
        (error "wrong password")))
  dispatch)
